name: cheviz
channels:
  - pytorch
  - fastai
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - attrs=19.3.0
  - backcall=0.1.0
  - beautifulsoup4=4.9.0
  - bleach=3.1.5
  - bottleneck=1.3.2
  - brotlipy=0.7.0
  - ca-certificates=2020.4.5.1
  - catalogue=1.0.0
  - certifi=2020.4.5.1
  - cffi=1.14.0
  - chardet=3.0.4
  - cryptography=2.9.2
  - cudatoolkit=10.1.243
  - cycler=0.10.0
  - cymem=2.0.3
  - cython-blis=0.4.1
  - dataclasses=0.7
  - dbus=1.13.6
  - decorator=4.4.2
  - defusedxml=0.6.0
  - entrypoints=0.3
  - expat=2.2.9
  - fastai=1.0.61
  - fastprogress=0.2.3
  - fontconfig=2.13.1
  - freetype=2.10.1
  - gettext=0.19.8.1
  - glib=2.64.2
  - gst-plugins-base=1.14.5
  - gstreamer=1.14.5
  - icu=64.2
  - idna=2.9
  - importlib-metadata=1.6.0
  - importlib_metadata=1.6.0
  - ipykernel=5.2.1
  - ipython=7.14.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.5.1
  - jedi=0.17.0
  - jinja2=2.11.2
  - jpeg=9c
  - json5=0.9.0
  - jsonschema=3.2.0
  - jupyter=1.0.0
  - jupyter_client=6.1.3
  - jupyter_console=6.1.0
  - jupyter_core=4.6.3
  - jupyterlab=2.1.2
  - jupyterlab_server=1.1.1
  - kiwisolver=1.2.0
  - ld_impl_linux-64=2.34
  - libblas=3.8.0
  - libcblas=3.8.0
  - libclang=9.0.1
  - libffi=3.2.1
  - libgcc-ng=9.2.0
  - libgfortran-ng=7.3.0
  - libiconv=1.15
  - liblapack=3.8.0
  - libllvm9=9.0.1
  - libopenblas=0.3.9
  - libpng=1.6.37
  - libsodium=1.0.17
  - libstdcxx-ng=9.2.0
  - libtiff=4.1.0
  - libuuid=2.32.1
  - libuv=1.34.0
  - libwebp-base=1.1.0
  - libxcb=1.13
  - libxkbcommon=0.10.0
  - libxml2=2.9.10
  - llvm-openmp=10.0.0
  - lz4-c=1.9.2
  - markupsafe=1.1.1
  - matplotlib=3.2.1
  - matplotlib-base=3.2.1
  - mistune=0.8.4
  - mkl=2020.1
  - murmurhash=1.0.0
  - nbconvert=5.6.1
  - nbformat=5.0.6
  - ncurses=6.1
  - ninja=1.10.0
  - nodejs=13.13.0
  - notebook=6.0.3
  - nspr=4.25
  - nss=3.47
  - numexpr=2.7.1
  - numpy=1.18.4
  - nvidia-ml-py3=7.352.0
  - olefile=0.46
  - openssl=1.1.1g
  - packaging=20.1
  - pandas=1.0.3
  - pandoc=2.9.2.1
  - pandocfilters=1.4.2
  - parso=0.7.0
  - pcre=8.44
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=7.1.2
  - pip=20.1
  - plac=0.9.6
  - preshed=3.0.2
  - prometheus_client=0.7.1
  - prompt-toolkit=3.0.5
  - prompt_toolkit=3.0.5
  - pthread-stubs=0.4
  - ptyprocess=0.6.0
  - pycparser=2.20
  - pygments=2.6.1
  - pyopenssl=19.1.0
  - pyparsing=2.4.7
  - pyqt=5.12.3
  - pyrsistent=0.16.0
  - pysocks=1.7.1
  - python=3.6.10
  - python-dateutil=2.8.1
  - python_abi=3.6
  - pytorch=1.4.0
  - pytz=2020.1
  - pyyaml=5.3.1
  - pyzmq=19.0.1
  - qt=5.12.5
  - qtconsole=4.7.3
  - qtpy=1.9.0
  - readline=8.0
  - requests=2.23.0
  - scipy=1.4.1
  - send2trash=1.5.0
  - setuptools=46.1.3
  - six=1.14.0
  - soupsieve=1.9.4
  - spacy=2.2.3
  - sqlite=3.30.1
  - srsly=1.0.0
  - terminado=0.8.3
  - testpath=0.4.4
  - thinc=7.3.0
  - tk=8.6.10
  - torchvision=0.5.0
  - tornado=6.0.4
  - tqdm=4.46.0
  - traitlets=4.3.3
  - urllib3=1.25.9
  - wasabi=0.6.0
  - wcwidth=0.1.9
  - webencodings=0.5.1
  - wheel=0.34.2
  - widgetsnbextension=3.5.1
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xz=5.2.5
  - yaml=0.2.4
  - zeromq=4.3.2
  - zipp=3.1.0
  - zlib=1.2.11
  - zstd=1.4.4
  - pip:
    - fastscript==0.1.4
    - nbdev==0.2.18
    - pyqt5-sip==4.19.18
    - pyqtchart==5.12
    - pyqtwebengine==5.12.1
    - python-chess==0.31.1
