# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"makeThreatenedSquares": "00_core.ipynb",
         "show": "00_core.ipynb",
         "defence": "00_core.ipynb",
         "attack": "00_core.ipynb",
         "fetch": "01_data.ipynb",
         "games": "01_data.ipynb",
         "makeMoveSequencer": "01_data.ipynb",
         "diffReduce": "01_data.ipynb",
         "makeDiffReduceAnalyzer": "01_data.ipynb",
         "zerosDiffReduce": "01_data.ipynb",
         "showGameUi": "02_ui.ipynb",
         "download": "03_stockfish.ipynb",
         "extract": "03_stockfish.ipynb"}

modules = ["core.py",
           "data.py",
           "ui.py",
           "stockfish.py"]

doc_url = "https://mikhas.github.io/cheviz/"

git_url = "https://github.com/mikhas/cheviz/tree/master/"

def custom_doc_links(name): return None
