# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"makeThreatenedSquares": "00_core.ipynb",
         "show": "00_core.ipynb",
         "defence": "00_core.ipynb",
         "attack": "00_core.ipynb",
         "fetch": "01_data.ipynb",
         "games": "01_data.ipynb",
         "makeMoveSequencer": "01_data.ipynb"}

modules = ["core.py",
           "data.py"]

doc_url = "https://fastai.github.io/cheviz/"

git_url = "https://github.com/fastai/cheviz/tree/master/"

def custom_doc_links(name): return None
