# AUTOGENERATED! DO NOT EDIT! File to edit: 01_data.ipynb (unless otherwise specified).

__all__ = ['fetch', 'from_game', 'games', 'makeMoveSequencer', 'diffReduce', 'makeDiffReduceAnalyzer',
           'zerosDiffReduce']

# Cell
from pathlib import Path
import urllib.request
import shutil

def fetch()->dict:
    result = {}
    url_prefix = 'https://pgnchessbook.org/wp-content/uploads/2019/08/'
    data_files = ['WorldChamp_1986_to_2018.pgn', 'Candidates_1953.pgn', 'WijkaanZee2019.pgn', 'Shamkir2019.pgn', 'Baden2019.pgn']

    for file in data_files:
        src = url_prefix + file
        dst = Path().absolute() / 'data' / file
        if not dst.is_file():
            with urllib.request.urlopen(src) as response, open(dst, 'wb') as dst_file:
                shutil.copyfileobj(response, dst_file)

        if dst.is_file():
            result[file] = dst

    return result

# Cell
import chess.pgn


def from_game(game:chess.pgn.Game)->tuple:
    return (game.board(), game.mainline_moves(), game.headers)


def games(pgn_name:str)->tuple:
    with open(pgn_name, 'r') as pgn_file:
        while True:
            game = chess.pgn.read_game(pgn_file)
            if game is None:
                break

            yield from_game(game)

# Cell
from typing import Callable
import numpy as np
from cheviz import core

def makeMoveSequencer(moves_list:list)->Callable:
    board = chess.Board()
    ts = core.makeThreatenedSquares(board=board)

    def moveSequencer(moves_range:range, side:bool, square_filter:Callable)->np.ndarray:
        result = []
        board.reset()

        for index in range(0, min(len(moves_list), moves_range.stop)):
            was_our_turn = board.turn == side # check *before* pushing next move
            adjusted_start = moves_range.start if was_our_turn else moves_range.start - 1
            board.push(moves_list[index])
            if index >= adjusted_start and was_our_turn:
                result.append(ts(side, square_filter))


        # if no move was found by moves_range, use initial board configuration instead:
        if len(result) == 0:
            result.append(ts(side, square_filter))

        return result

    return moveSequencer

# Cell
def diffReduce(data:list):
    while len(data) > 1:
        data = [data[i] - data[i + 1] for i in range(len(data) - 1)]
    data = data.pop() if len(data) == 1 else np.zeros(core.dimension() ** 2)
    return data

# Cell
def makeDiffReduceAnalyzer(move_list:list, square_filter:Callable)->Callable:
    ms = makeMoveSequencer(moves_list)

    def analyzer(mr:range, side:bool)->np.ndarray:
        return diffReduce(ms(mr, side, square_filter))

    return analyzer


def zerosDiffReduce(moves_total:int, move_window_size:int, side:bool, analyzer:Callable)->list:
    result = []
    for i in range(0 if side else 1, moves_total, 2):
        data = analyzer(range(i, i + move_window_size), side)
        unique, counts = np.unique(data, return_counts=True)
        result.append(dict(zip(unique, counts))[0])
    return result