# AUTOGENERATED! DO NOT EDIT! File to edit: 01_data.ipynb (unless otherwise specified).

__all__ = ['fetch', 'games']

# Cell
from pathlib import Path
import urllib.request
import shutil

def fetch()->dict:
    result = {}
    url_prefix = 'https://pgnchessbook.org/wp-content/uploads/2019/08/'
    data_files = ['WorldChamp_1986_to_2018.pgn', 'Candidates_1953.pgn', 'WijkaanZee2019.pgn', 'Shamkir2019.pgn', 'Baden2019.pgn']

    for file in data_files:
        src = url_prefix + file
        dst = Path().absolute() / 'data' / file
        if not dst.is_file():
            with urllib.request.urlopen(src) as response, open(dst, 'wb') as dst_file:
                shutil.copyfileobj(response, dst_file)
            #!curl -o '{dst}' '{src}'

        if dst.is_file():
            result[file] = dst

    return result

# Cell
import chess.pgn

def games(pgn_name:str)->chess.pgn.Game:
    with open(pgn_name, 'r') as pgn_file:
        games_read = []
        while True:
            game = chess.pgn.read_game(pgn_file)
            if game is None:
                break

            yield (game.board(), game.mainline_moves(), game.headers)