# AUTOGENERATED! DO NOT EDIT! File to edit: 03_stockfish.ipynb (unless otherwise specified).

__all__ = ['download', 'extract', 'playGame']

# Cell
from pathlib import Path
import urllib.request
import shutil

def download():
    src = 'https://stockfishchess.org/files/stockfish-11-linux.zip'
    dst = Path().absolute() / 'tools' / 'stockfish.zip'

    if not dst.is_file():
        request = urllib.request.Request(src)
        request.add_header('Referer', 'https://stockfishchess.org/download/')
        request.add_header('User-Agent', 'Mozilla/5.0 (Windows NT 6.1; Win64; x64)')

        with urllib.request.urlopen(request) as response, open(dst, 'wb') as dst_file:
            shutil.copyfileobj(response, dst_file)

    return dst

# Cell
from pathlib import Path
import zipfile
import os
import stat

def extract(dst:Path):
    if not dst.is_file():
        return

    with zipfile.ZipFile(dst, 'r') as zip_file:
        zip_file.extractall(Path().absolute() / 'tools')
        dst_extracted = Path().absolute() / 'tools' / zip_file.namelist()[0]

        # make binary executable
        dst_binary = dst_extracted / 'Linux' / 'stockfish_20011801_x64'
        st = os.stat(dst_binary)
        os.chmod(dst_binary, st.st_mode | stat.S_IEXEC)

        return dst_binary

# Cell
from pathlib import Path
import chess
import chess.engine
import chess.pgn
import cheviz.data
import datetime

def playGame(engine_path:Path, time_limit:float=0.1):
    engine = chess.engine.SimpleEngine.popen_uci(engine_path.as_posix())
    game = chess.pgn.Game()
    game.headers['Event'] = 'cheviz'
    game.headers['Date'] = datetime.date.today().strftime("%Y-%m-%d")
    game.headers['White'] = engine_path.name
    game.headers['Black'] = engine_path.name

    while not game.board().is_game_over():
        result = engine.play(game.board(), chess.engine.Limit(time=time_limit), info=chess.engine.Info.SCORE)
        game = game.add_main_variation(result.move)
        # result.info is sometimes empty, happens more reliably with very short time limits
        game.comment = result.info['score'] if 'score' in result.info else None

    engine.quit()
    # set game back to root node
    game = game.game()
    game.headers['Result'] = game.board().result

    return game