# AUTOGENERATED! DO NOT EDIT! File to edit: 03_stockfish.ipynb (unless otherwise specified).

__all__ = ['download', 'extract']

# Cell
from pathlib import Path
import urllib.request
import shutil

def download():
    src = 'https://stockfishchess.org/files/stockfish-11-linux.zip'
    dst = Path().absolute() / 'tools' / 'stockfish.zip'

    if not dst.is_file():
        request = urllib.request.Request(src)
        request.add_header('Referer', 'https://stockfishchess.org/download/')
        request.add_header('User-Agent', 'Mozilla/5.0 (Windows NT 6.1; Win64; x64)')

        with urllib.request.urlopen(request) as response, open(dst, 'wb') as dst_file:
            shutil.copyfileobj(response, dst_file)

    return dst

# Cell
from pathlib import Path
import zipfile
import os
import stat

def extract(dst:Path):
    if not dst.is_file():
        return

    with zipfile.ZipFile(dst, 'r') as zip_file:
        zip_file.extractall(Path().absolute() / 'tools')
        dst_extracted = Path().absolute() / 'tools' / zip_file.namelist()[0]

        # make binary executable
        dst_binary = dst_extracted / 'Linux' / 'stockfish_20011801_x64'
        st = os.stat(dst_binary)
        os.chmod(dst_binary, st.st_mode | stat.S_IEXEC)

        return dst_binary